# Generated by Django 4.2.7 on 2023-11-16 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0002_comment_priority_task_owner_task_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='value',
        ),
        migrations.AddField(
            model_name='priority',
            name='priority',
            field=models.CharField(choices=[(1, 'Default'), (2, 'Low'), (3, 'Medium'), (4, 'High')], default='Default', max_length=10, verbose_name='Priority value'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Task name'),
        ),
    ]
