# Generated by Django 4.2.7 on 2023-11-16 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0003_remove_priority_value_priority_priority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='priority',
            old_name='priority',
            new_name='value',
        ),
    ]
