# Generated by Django 4.2.7 on 2023-11-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0005_alter_priority_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='value',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Low'), (3, 'Medium'), (4, 'High')], default=1, verbose_name='Priority value'),
        ),
    ]
