# Generated by Django 4.2.7 on 2023-11-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0008_alter_task_priority_delete_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Default'), (2, 'Low'), (3, 'Medium'), (4, 'High')], default='Default', verbose_name='Priority value'),
        ),
    ]
