# Generated by Django 4.2.7 on 2023-11-16 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0009_alter_task_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('Default', 'Default'), ('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Default', max_length=15, verbose_name='Priority value'),
        ),
    ]
