# Generated by Django 4.2.7 on 2023-12-02 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0016_comment_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommonTask',
        ),
    ]
